name: epic2023
description: Terminal Management System for 2023 Engineering Practice and Innovation Competition
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  media_kit: ^1.1.7
  media_kit_video: ^1.1.8
  media_kit_libs_video: ^1.0.1
  animations: ^2.0.8
  fl_chart: ^0.63.0
  provider: ^6.0.5
  path_provider: ^2.1.1
  window_manager: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/videos/video.mp4
    - assets/videos/test.mp4

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
#    - family: Alibaba_PuHuiTi
#      fonts:
#        - asset: fonts/Alibaba_PuHuiTi_2.0_35_Thin_35_Thin.ttf
#          weight: 100
#        - asset: fonts/Alibaba_PuHuiTi_2.0_45_Light_45_Light.ttf
#          weight: 200
#        - asset: fonts/Alibaba_PuHuiTi_2.0_55_Regular_55_Regular.ttf
#          weight: 300
#        - asset: fonts/Alibaba_PuHuiTi_2.0_65_Medium_65_Medium.ttf
#          weight: 400
#        - asset: fonts/Alibaba_PuHuiTi_2.0_55_Regular_85_Bold.ttf
#          weight: 500
#        - asset: fonts/Alibaba_PuHuiTi_2.0_105_Heavy_105_Heavy.ttf
#          weight: 600
#        - asset: fonts/Alibaba_PuHuiTi_2.0_115_Black_115_Black.ttf
#          weight: 700

    - family: NotoSansSC
      fonts:
        - asset: fonts/NotoSans/NotoSansSC-Thin.ttf
          weight: 100
        - asset: fonts/NotoSans/NotoSansSC-Light.ttf
          weight: 300
        - asset: fonts/NotoSans/NotoSansSC-Regular.ttf
          weight: 400
        - asset: fonts/NotoSans/NotoSansSC-Medium.ttf
          weight: 500
        - asset: fonts/NotoSans/NotoSansSC-Bold.ttf
          weight: 700
        - asset: fonts/NotoSans/NotoSansSC-Black.ttf
          weight: 900

    - family: JetBrainsMono
      fonts:
        - asset: fonts/JetBrainsMono/JetBrainsMono-Thin.ttf
          weight: 100
          style: normal
        - asset: fonts/JetBrainsMono/JetBrainsMono-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/JetBrainsMono/JetBrainsMono-ExtraLight.ttf
          weight: 200
          style: normal
        - asset: fonts/JetBrainsMono/JetBrainsMono-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/JetBrainsMono/JetBrainsMono-Light.ttf
          weight: 300
          style: normal
        - asset: fonts/JetBrainsMono/JetBrainsMono-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/JetBrainsMono/JetBrainsMono-Regular.ttf
          weight: 400
          style: normal
        - asset: fonts/JetBrainsMono/JetBrainsMono-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/JetBrainsMono/JetBrainsMono-Medium.ttf
          weight: 500
          style: normal
        - asset: fonts/JetBrainsMono/JetBrainsMono-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/JetBrainsMono/JetBrainsMono-SemiBold.ttf
          weight: 600
          style: normal
        - asset: fonts/JetBrainsMono/JetBrainsMono-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/JetBrainsMono/JetBrainsMono-Bold.ttf
          weight: 700
          style: normal
        - asset: fonts/JetBrainsMono/JetBrainsMono-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/JetBrainsMono/JetBrainsMono-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: fonts/JetBrainsMono/JetBrainsMono-ExtraBoldItalic.ttf
          weight: 800
          style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
